# Generated by Django 3.2.11 on 2022-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.AddField(
            model_name='image',
            name='ISO',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='aperture',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='artist',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='cameraMode',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='colorSpace',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='exposure',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='exposureCompensation',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='filetype',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='flash',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='focalLength',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='fstop',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='lensModel',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='meteringMode',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='originalDate',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='shutterSpeed',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='software',
            field=models.CharField(blank=True, default='', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='images',
            field=models.ManyToManyField(blank=True, default='', to='blog.Image'),
        ),
    ]
